### ISSUE TITLE
`\othertitle` does not seem to work as intended

### ISSUE THREAD

**Issue by jiahuei** [liantze/umalayathesis#2]
`\othertitle` does not seem to appear above the Malay abstract, even when defined.

Thanks !

**Comment by liantze** [comment]
Argh, definitely a bug. Now fixed with v1.5.1, which also now switches to use `natbib` citation commands. Therefore please use `\citep`, `\citet` instead of `\cite`, `\citeA` from now on. Thanks for the report!

**Comment by jiahuei** [comment]
Thanks so much for the quick fix 👍
