### ISSUE TITLE
Changes to cover pages (University of Malaya to Universiti Malaya)

### ISSUE THREAD

**Issue by hongvin** [liantze/umalayathesis#4]
The official English name of the university is now Universiti Malaya. This affects the cover page, the wording in the declaration page.

~Edit: The citation format is now APA 7. I will try to port to `biblatex-apa` and PR later.~ Found a blog [here](https://tex.my/2022/05/28/using-apa7-with-umalayathesis/)

**Comment by hongvin** [comment]
The official DOCX template is as attached.
[8.  Format of Thesis  Dissertation (3).docx](https://github.com/liantze/umalayathesis/files/10292127/8.Format.of.Thesis.Dissertation.3.docx)

**Comment by liantze** [comment]
Copy and paste
```latex
\makeatletter
\patchcmd{\makecoverandtitlepage}{UNIVERSITY OF MALAYA}{UNIVERSITI MALAYA}{}{}
\patchcmd{\faculty@block}{UNIVERSITY OF MALAYA}{UNIVERSITI MALAYA}{}{}
\makeatother
```
before `\begin{document}` of `thesis.tex` for now, pending future update of `umalayathesis.cls` itself.
